### ISSUE TITLE
Crear formulario registro y login

### ISSUE THREAD

**Issue by marianobazanc** [G5-ISPC2023/G5-ISPC2023#1]
Crear con HTML y Bootstrap un formulario **SIN JAVASCRIPT** que cumpla con los siguientes requisitos:

**Formulario registro:**
- > Nombre
- > Email
- > Contraseña
- > Repetir constraseña
- > Aceptar terminos
- > Boton de registro
- > Link que redirija al login en caso de ya tener una cuenta

**Formulario Login**
- > Email
- > Contraseña
- > Boton login
- > Link que redirija al registro en caso de no tener una cuenta

**Comment by marianobazanc** [comment]
Creo archivo css con el fin de crear una variable asignando el color celeste caracteristico del ISPC

**Comment by marianobazanc** [comment]
Hago push del maquetado actual. Quedo a la espera de comentarios

**Comment by Juancalero01** [comment]
Genial, muy bien implementado. Por mi lo pasaria a finalizado.
