### ISSUE TITLE
Crear footer

### ISSUE THREAD

**Issue by marianobazanc** [G5-ISPC2023/G5-ISPC2023#10]

**Comment by Juancalero01** [comment]
Para revision, misma logica que el navbar tiene dos footer dependiendo quien lo ve. (Guest/User)

**Comment by Juancalero01** [comment]
![Image](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/73122175/26f45e92-dbbb-41ac-b9c9-51a6a6b38583)
