### ISSUE TITLE
Crear cotizaciones de acciones

### ISSUE THREAD

**Issue by NazarenoCarlesso** [G5-ISPC2023/G5-ISPC2023#2]
Crear un listado de cotizaciones de acciones

Requisitos:

- Debe mostrar el nombre de la acción

![Image](https://user-images.githubusercontent.com/95937325/253058016-e8b0fe71-62f2-46eb-acdb-1e4d9d66b489.png)

**Comment by marianobazanc** [comment]
- Agregar navbar y footer
- En lo posible agregar mas opciones para que sea "mas realista"

- En mobile se rompe por completo (se puede solucionar quitando opciones no tan necesarias en caso de ser vista mobila o utilizar "table-responsive" de bootstrap), recomiendo observar como reacciona la pagina original ante la vista mobile


![Image](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/83035202/6d4551ff-208e-4312-ac75-e728e720ae28)
