### ISSUE TITLE
Añadir logica a formulario "Compra de acciones"

### ISSUE THREAD

**Issue by Nass203** [G5-ISPC2023/G5-ISPC2023#21]
Eliminar:
1- Forma de pago (ya que el pago se efectuara con la plata que el usuario tenga en su billetera virtual)

Añadir:
1- En el select, la lista de acciones disponibles. Dicho dato se encuentra en el JSON
2- Precio por unidad de accion segun la accion seleccionada
3- Al hacer click en recibo (con todos los datos bien añadidos) que aparezca el componente para confirmar la compra
4- El componente de la info de compra debe tener la info correcta

5- Colores correctos segun paleta de color
6- Usar todo el bootstrap posible
7- Boton de bootstrap de color verde

Validaciones:
1- La cantidad a comprar debe ser mayor a 0 y de tipo numerico. Mostrar el mensaje de error correspondiente
2- Si al tocar "Recibo" no hay una cantidad designada o una accion seleccionada ejecutar un mensaje de error

**Comment by marianobazanc** [comment]
Muy bueno! Aprobado
