### ISSUE TITLE
Añadir logica y estandarizar Navbar y footer

### ISSUE THREAD

**Issue by Juancalero01** [G5-ISPC2023/G5-ISPC2023#24]
** NAVBAR **
 
Validaciones:
1- Mostrar "Iniciar sesion" si el usuario no está con una sesion iniciada
2- Mostrar "Cerrar sesión" si el usuario está con la sesion iniciada
3- Mostrar "Comprar" y "Dashboard" solo si el usuario tiene una sesion iniciada
4- Poner el nombre del usuario en el navbar

Añadir:
1- Utilizar paleta de color correspondiente

** FOOTER **
Añadir:
1- Colores segun paleta de colores

**Comment by Juancalero01** [comment]
Footer realizado, aunque no tengo un archivo donde dice la paleta de colores, espero a que este realizado para su dicha actualización de estilos.

**Comment by marianobazanc** [comment]
Se le sumo guard y behaviorsubject
