### ISSUE TITLE
Crear página "Quienes somos"

### ISSUE THREAD

**Issue by LorenzoPurro** [G5-ISPC2023/G5-ISPC2023#3]
+ Debe seguir la estética establecida
+ Barra inferior con "datos de contacto" 
+ Textos que establezcan quienes somos y partners

**Comment by LorenzoPurro** [comment]
![Desktop Screenshot 2023 07 14 - 19 15 05 17](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/135060467/68729e7e-1d96-488c-bd94-fdd486d7a6ed)
Mockup del objetivo de layout, se reciben ideas

**Comment by Juancalero01** [comment]
- Genial, lo unico que no me cuadra es que tiene otro navbar arriba.
- Luego en conocenos pondria el nombre de los integrantes sin foto no importa que sea una foto por defecto. 
- Los nuestros partnerts, lo scaria pero si queres dejalo pero ponele unas imagenes

**Comment by marianobazanc** [comment]
En mobile se rompe algun margen hay que revisar, pero no es grave. Cumple con lo que promete, me gusta y personalmente está aprobado :)
