### ISSUE TITLE
us-05 Crear landing page

### ISSUE THREAD

**Issue by lorenareichel** [G5-ISPC2023/G5-ISPC2023#5]

**Comment by Juancalero01** [comment]
Para revisión.

**Comment by marianobazanc** [comment]
- El <main> en reponsive a partir de 361px para abajo es tapado por el navbar.


![Image](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/83035202/1ac6fe95-b1ed-4636-8685-a51c5a31dd97)



- Los cards en mobile se rompen y salen del DOM creo que mejor seria que sea uno abajo de otro


![Image](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/83035202/d2e91d6c-ee09-434b-8e87-23b10ba5ab59)


- A mejorar algunos aspectos de margenes 

Opinion final: Me parece muuy buena la pagina, considero que ya se puede aprobar para produccion y en lo que pase el tiempo mejorar los errores
