### ISSUE TITLE
Crear formulario operacion de compras de acciones

### ISSUE THREAD

**Issue by lorenareichel** [G5-ISPC2023/G5-ISPC2023#6]

**Comment by marianobazanc** [comment]
-El maquetado en version "desktop" está correcto

-No cumple en ser responsive. A partir de 421px X 760px se rompe. Lo ideal seria que el div "Recibo" vaya para abajo en determinado tamaño

![Image](https://github.com/G5-ISPC2023/G5-ISPC2023/assets/83035202/a27d91ab-c460-4f66-8c39-cc6cadd67a3f)



-Animación: Esta buena, pero por el momento no veo necesaria una animación. Ya que en un futuro al incluirlo podriamos utilizar librerias que facilitan ese trabajo

**Comment by Juancalero01** [comment]
- Maquetado: Al responsive le pusiste 421px(Muy justo) te recomendaría que empieces  425px. o superior 450px ve probando. 
- El navbar le pusiste la etiqueta object (No esta mal pero se rompe el navbar), te recomiendo quitarlo o copiar el código del html del navbar.
- El resto está todo bien.

**Comment by marianobazanc** [comment]
Me gusta, como maquetado me parece bien. Personalmente aprobado! :)
